//! QuickJS Opcode Definitions
//! AUTO-GENERATED from quickjs-opcode.h - DO NOT EDIT MANUALLY
//!
//! Regenerate with: zig build gen-opcodes
//! Source: vendor/quickjs-ng/quickjs-opcode.h

const std = @import("std");

/// Instruction format types
pub const Format = enum {
    none,
    none_int,
    none_loc,
    none_arg,
    none_var_ref,
    u8,
    i8,
    loc8,
    const8,
    label8,
    u16,
    i16,
    label16,
    npop,
    npopx,
    npop_u16,
    loc,
    arg,
    var_ref,
    u32,
    u32x2,
    i32,
    @"const",
    label,
    atom,
    atom_u8,
    atom_u16,
    atom_label_u8,
    atom_label_u16,
    label_u16,
};

pub const Opcode = enum(u8) {
    invalid = 0,
    push_i32 = 1,
    push_const = 2,
    fclosure = 3,
    push_atom_value = 4,
    private_symbol = 5,
    undefined = 6,
    null = 7,
    push_this = 8,
    push_false = 9,
    push_true = 10,
    object = 11,
    special_object = 12,
    rest = 13,
    drop = 14,
    nip = 15,
    nip1 = 16,
    dup = 17,
    dup1 = 18,
    dup2 = 19,
    dup3 = 20,
    insert2 = 21,
    insert3 = 22,
    insert4 = 23,
    perm3 = 24,
    perm4 = 25,
    perm5 = 26,
    swap = 27,
    swap2 = 28,
    rot3l = 29,
    rot3r = 30,
    rot4l = 31,
    rot5l = 32,
    call_constructor = 33,
    call = 34,
    tail_call = 35,
    call_method = 36,
    tail_call_method = 37,
    array_from = 38,
    apply = 39,
    @"return" = 40,
    return_undef = 41,
    check_ctor_return = 42,
    check_ctor = 43,
    init_ctor = 44,
    check_brand = 45,
    add_brand = 46,
    return_async = 47,
    throw = 48,
    throw_error = 49,
    eval = 50,
    apply_eval = 51,
    regexp = 52,
    get_super = 53,
    import = 54,
    check_var = 55,
    get_var_undef = 56,
    get_var = 57,
    put_var = 58,
    put_var_init = 59,
    put_var_strict = 60,
    get_ref_value = 61,
    put_ref_value = 62,
    define_var = 63,
    check_define_var = 64,
    define_func = 65,
    get_field = 66,
    get_field2 = 67,
    put_field = 68,
    get_private_field = 69,
    put_private_field = 70,
    define_private_field = 71,
    get_array_el = 72,
    get_array_el2 = 73,
    put_array_el = 74,
    get_super_value = 75,
    put_super_value = 76,
    define_field = 77,
    set_name = 78,
    set_name_computed = 79,
    set_proto = 80,
    set_home_object = 81,
    define_array_el = 82,
    append = 83,
    copy_data_properties = 84,
    define_method = 85,
    define_method_computed = 86,
    define_class = 87,
    define_class_computed = 88,
    get_loc = 89,
    put_loc = 90,
    set_loc = 91,
    get_arg = 92,
    put_arg = 93,
    set_arg = 94,
    get_var_ref = 95,
    put_var_ref = 96,
    set_var_ref = 97,
    set_loc_uninitialized = 98,
    get_loc_check = 99,
    put_loc_check = 100,
    put_loc_check_init = 101,
    get_var_ref_check = 102,
    put_var_ref_check = 103,
    put_var_ref_check_init = 104,
    close_loc = 105,
    if_false = 106,
    if_true = 107,
    goto = 108,
    catch = 109,
    gosub = 110,
    ret = 111,
    nip_catch = 112,
    to_object = 113,
    to_string = 114,
    to_propkey = 115,
    to_propkey2 = 116,
    with_get_var = 117,
    with_put_var = 118,
    with_delete_var = 119,
    with_make_ref = 120,
    with_get_ref = 121,
    with_get_ref_undef = 122,
    make_loc_ref = 123,
    make_arg_ref = 124,
    make_var_ref_ref = 125,
    make_var_ref = 126,
    for_in_start = 127,
    for_of_start = 128,
    for_await_of_start = 129,
    for_in_next = 130,
    for_of_next = 131,
    iterator_check_object = 132,
    iterator_get_value_done = 133,
    iterator_close = 134,
    iterator_next = 135,
    iterator_call = 136,
    initial_yield = 137,
    yield = 138,
    yield_star = 139,
    async_yield_star = 140,
    await = 141,
    neg = 142,
    plus = 143,
    dec = 144,
    inc = 145,
    post_dec = 146,
    post_inc = 147,
    dec_loc = 148,
    inc_loc = 149,
    add_loc = 150,
    not = 151,
    lnot = 152,
    typeof = 153,
    delete = 154,
    delete_var = 155,
    mul = 156,
    div = 157,
    mod = 158,
    add = 159,
    sub = 160,
    shl = 161,
    sar = 162,
    shr = 163,
    @"and" = 164,
    xor = 165,
    @"or" = 166,
    pow = 167,
    lt = 168,
    lte = 169,
    gt = 170,
    gte = 171,
    instanceof = 172,
    in = 173,
    eq = 174,
    neq = 175,
    strict_eq = 176,
    strict_neq = 177,
    is_undefined_or_null = 178,
    private_in = 179,
    push_bigint_i32 = 180,
    nop = 181,
    enter_scope = 182,
    leave_scope = 183,
    label = 184,
    scope_get_var_undef = 185,
    scope_get_var = 186,
    scope_put_var = 187,
    scope_delete_var = 188,
    scope_make_ref = 189,
    scope_get_ref = 190,
    scope_put_var_init = 191,
    scope_get_private_field = 192,
    scope_get_private_field2 = 193,
    scope_put_private_field = 194,
    scope_in_private_field = 195,
    get_field_opt_chain = 196,
    get_array_el_opt_chain = 197,
    set_class_name = 198,
    source_loc = 199,
    push_minus1 = 200,
    push_0 = 201,
    push_1 = 202,
    push_2 = 203,
    push_3 = 204,
    push_4 = 205,
    push_5 = 206,
    push_6 = 207,
    push_7 = 208,
    push_i8 = 209,
    push_i16 = 210,
    push_const8 = 211,
    fclosure8 = 212,
    push_empty_string = 213,
    get_loc8 = 214,
    put_loc8 = 215,
    set_loc8 = 216,
    get_loc0_loc1 = 217,
    get_loc0 = 218,
    get_loc1 = 219,
    get_loc2 = 220,
    get_loc3 = 221,
    put_loc0 = 222,
    put_loc1 = 223,
    put_loc2 = 224,
    put_loc3 = 225,
    set_loc0 = 226,
    set_loc1 = 227,
    set_loc2 = 228,
    set_loc3 = 229,
    get_arg0 = 230,
    get_arg1 = 231,
    get_arg2 = 232,
    get_arg3 = 233,
    put_arg0 = 234,
    put_arg1 = 235,
    put_arg2 = 236,
    put_arg3 = 237,
    set_arg0 = 238,
    set_arg1 = 239,
    set_arg2 = 240,
    set_arg3 = 241,
    get_var_ref0 = 242,
    get_var_ref1 = 243,
    get_var_ref2 = 244,
    get_var_ref3 = 245,
    put_var_ref0 = 246,
    put_var_ref1 = 247,
    put_var_ref2 = 248,
    put_var_ref3 = 249,
    set_var_ref0 = 250,
    set_var_ref1 = 251,
    set_var_ref2 = 252,
    set_var_ref3 = 253,
    get_length = 254,
    if_false8 = 255,
    if_true8 = 256,
    goto8 = 257,
    goto16 = 258,
    call0 = 259,
    call1 = 260,
    call2 = 261,
    call3 = 262,
    is_undefined = 263,
    is_null = 264,
    typeof_is_undefined = 265,
    typeof_is_function = 266,

    pub fn name(self: Opcode) []const u8 {
        return @tagName(self);
    }
};

pub const OPCODE_COUNT: u16 =267;

/// Opcode metadata: size, stack effects, format
pub const OpcodeInfo = struct {
    size: u8,
    n_pop: u8,
    n_push: u8,
    format: Format,
    is_temp: bool,
};

pub const opcode_info = [_]OpcodeInfo{
    .{ .size = 1, .n_pop = 0, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .i32, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .@"const", .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .@"const", .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 1, .format = .u8, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .u16, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 4, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 6, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 4, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 4, .n_push = 5, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 4, .n_push = 4, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 5, .n_push = 5, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 4, .n_push = 4, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 4, .n_push = 4, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 5, .n_push = 5, .format = .none, .is_temp = false },
    .{ .size = 3, .n_pop = 2, .n_push = 1, .format = .npop, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 1, .format = .npop, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .npop, .is_temp = false },
    .{ .size = 3, .n_pop = 2, .n_push = 1, .format = .npop, .is_temp = false },
    .{ .size = 3, .n_pop = 2, .n_push = 0, .format = .npop, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .npop, .is_temp = false },
    .{ .size = 3, .n_pop = 3, .n_push = 1, .format = .u16, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 6, .n_pop = 0, .n_push = 0, .format = .atom_u8, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 1, .format = .npop_u16, .is_temp = false },
    .{ .size = 3, .n_pop = 2, .n_push = 1, .format = .u16, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 0, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 0, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 2, .n_push = 0, .format = .atom, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 6, .n_pop = 0, .n_push = 0, .format = .atom_u8, .is_temp = false },
    .{ .size = 6, .n_pop = 0, .n_push = 0, .format = .atom_u8, .is_temp = false },
    .{ .size = 6, .n_pop = 1, .n_push = 0, .format = .atom_u8, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 2, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 2, .n_push = 0, .format = .atom, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 4, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 5, .n_pop = 2, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 2, .n_pop = 3, .n_push = 3, .format = .u8, .is_temp = false },
    .{ .size = 6, .n_pop = 2, .n_push = 1, .format = .atom_u8, .is_temp = false },
    .{ .size = 2, .n_pop = 3, .n_push = 1, .format = .u8, .is_temp = false },
    .{ .size = 6, .n_pop = 2, .n_push = 2, .format = .atom_u8, .is_temp = false },
    .{ .size = 6, .n_pop = 3, .n_push = 3, .format = .atom_u8, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .loc, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .loc, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 1, .format = .loc, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .arg, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .arg, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 1, .format = .arg, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .var_ref, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .var_ref, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 1, .format = .var_ref, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 0, .format = .loc, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .loc, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .loc, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .loc, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .var_ref, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .var_ref, .is_temp = false },
    .{ .size = 3, .n_pop = 1, .n_push = 0, .format = .var_ref, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 0, .format = .loc, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 0, .format = .label, .is_temp = false },
    .{ .size = 5, .n_pop = 1, .n_push = 0, .format = .label, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 0, .format = .label, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .label, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 0, .format = .label, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 10, .n_pop = 1, .n_push = 0, .format = .atom_label_u8, .is_temp = false },
    .{ .size = 10, .n_pop = 2, .n_push = 1, .format = .atom_label_u8, .is_temp = false },
    .{ .size = 10, .n_pop = 1, .n_push = 0, .format = .atom_label_u8, .is_temp = false },
    .{ .size = 10, .n_pop = 1, .n_push = 0, .format = .atom_label_u8, .is_temp = false },
    .{ .size = 10, .n_pop = 1, .n_push = 0, .format = .atom_label_u8, .is_temp = false },
    .{ .size = 10, .n_pop = 1, .n_push = 0, .format = .atom_label_u8, .is_temp = false },
    .{ .size = 7, .n_pop = 0, .n_push = 2, .format = .atom_u16, .is_temp = false },
    .{ .size = 7, .n_pop = 0, .n_push = 2, .format = .atom_u16, .is_temp = false },
    .{ .size = 7, .n_pop = 0, .n_push = 2, .format = .atom_u16, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 2, .format = .atom, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 3, .format = .none, .is_temp = false },
    .{ .size = 2, .n_pop = 3, .n_push = 5, .format = .u8, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 3, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 4, .n_push = 4, .format = .none, .is_temp = false },
    .{ .size = 2, .n_pop = 4, .n_push = 5, .format = .u8, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 2, .format = .none, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 0, .format = .loc8, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 0, .format = .loc8, .is_temp = false },
    .{ .size = 2, .n_pop = 1, .n_push = 0, .format = .loc8, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .atom, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 5, .n_pop = 0, .n_push = 1, .format = .i32, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 0, .format = .none, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 0, .format = .u16, .is_temp = true },
    .{ .size = 3, .n_pop = 0, .n_push = 0, .format = .u16, .is_temp = true },
    .{ .size = 5, .n_pop = 0, .n_push = 0, .format = .label, .is_temp = true },
    .{ .size = 7, .n_pop = 0, .n_push = 1, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 0, .n_push = 1, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 1, .n_push = 0, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 0, .n_push = 1, .format = .atom_u16, .is_temp = true },
    .{ .size = 11, .n_pop = 0, .n_push = 2, .format = .atom_label_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 0, .n_push = 2, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 0, .n_push = 2, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 1, .n_push = 1, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 1, .n_push = 2, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 2, .n_push = 0, .format = .atom_u16, .is_temp = true },
    .{ .size = 7, .n_pop = 1, .n_push = 1, .format = .atom_u16, .is_temp = true },
    .{ .size = 5, .n_pop = 1, .n_push = 1, .format = .atom, .is_temp = true },
    .{ .size = 1, .n_pop = 2, .n_push = 1, .format = .none, .is_temp = true },
    .{ .size = 5, .n_pop = 1, .n_push = 1, .format = .u32, .is_temp = true },
    .{ .size = 9, .n_pop = 0, .n_push = 0, .format = .u32x2, .is_temp = true },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_int, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 1, .format = .i8, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 1, .format = .i16, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 1, .format = .const8, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 1, .format = .const8, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 1, .format = .loc8, .is_temp = false },
    .{ .size = 2, .n_pop = 1, .n_push = 0, .format = .loc8, .is_temp = false },
    .{ .size = 2, .n_pop = 1, .n_push = 1, .format = .loc8, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 2, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_loc, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_arg, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 0, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 0, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none_var_ref, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 2, .n_pop = 1, .n_push = 0, .format = .label8, .is_temp = false },
    .{ .size = 2, .n_pop = 1, .n_push = 0, .format = .label8, .is_temp = false },
    .{ .size = 2, .n_pop = 0, .n_push = 0, .format = .label8, .is_temp = false },
    .{ .size = 3, .n_pop = 0, .n_push = 0, .format = .label16, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .npopx, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .npopx, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .npopx, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .npopx, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
    .{ .size = 1, .n_pop = 1, .n_push = 1, .format = .none, .is_temp = false },
};

/// Get metadata for an opcode
pub fn getInfo(op: Opcode) OpcodeInfo {
    return opcode_info[@intFromEnum(op)];
}

/// Get instruction size for an opcode
pub fn getSize(op: Opcode) u8 {
    return opcode_info[@intFromEnum(op)].size;
}
