name: 'Setup EdgeBox'
description: 'Setup EdgeBox build environment with all dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '20'
  install-hyperfine:
    description: 'Install hyperfine for benchmarking'
    required: false
    default: 'false'
  install-porffor:
    description: 'Install Porffor JS-to-WASM compiler'
    required: false
    default: 'false'
  build-test262:
    description: 'Build test262 runner'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    # === Tool Setup (always needed) ===
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Porffor
      if: inputs.install-porffor == 'true'
      shell: bash
      run: npm install -g porffor

    - name: Install hyperfine
      if: inputs.install-hyperfine == 'true'
      shell: bash
      run: |
        wget -q https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-musl_1.20.0_amd64.deb
        sudo dpkg -i hyperfine-musl_1.20.0_amd64.deb

    - name: Install build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-18-dev cmake ninja-build

    # === Cache ALL build outputs ===
    - name: Cache EdgeBox build
      id: cache-edgebox
      uses: actions/cache@v4
      with:
        path: |
          zig-out/bin/
          vendor/binaryen/
          vendor/wamr/product-mini/platforms/linux/build/
          vendor/wamr/wamr-compiler/build/
        key: edgebox-full-${{ runner.os }}-${{ hashFiles('build.zig', 'scripts/build-wamr.sh', 'vendor/wamr/core/version.h', 'src/**/*.zig') }}

    # === Build Binaryen (if cache miss) ===
    - name: Build Binaryen
      if: steps.cache-edgebox.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # Clone binaryen if not exists (not a submodule)
        if [ ! -d vendor/binaryen ]; then
          git clone --depth 1 --branch version_119 https://github.com/WebAssembly/binaryen.git vendor/binaryen
        fi
        cd vendor/binaryen
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF .
        ninja -C build
        # Install system-wide for Zig to find
        sudo ninja -C build install
        sudo ldconfig

    # === Build WAMR (if cache miss) ===
    - name: Build WAMR
      if: steps.cache-edgebox.outputs.cache-hit != 'true'
      shell: bash
      run: ./scripts/build-wamr.sh

    # === Build EdgeBox (if cache miss) ===
    - name: Build EdgeBox
      if: steps.cache-edgebox.outputs.cache-hit != 'true'
      shell: bash
      run: |
        zig build wasm -Doptimize=ReleaseFast
        zig build runner -Doptimize=ReleaseFast
        zig build cli -Doptimize=ReleaseFast
        ${{ inputs.build-test262 == 'true' && 'zig build test262 -Doptimize=ReleaseFast' || '' }}

    # === Install binaryen system-wide (on cache hit, since build step is skipped) ===
    - name: Install Binaryen (cache hit)
      if: steps.cache-edgebox.outputs.cache-hit == 'true'
      shell: bash
      run: |
        cd vendor/binaryen
        sudo ninja -C build install
        sudo ldconfig

    # === Setup environment (always needed, even on cache hit) ===
    - name: Setup paths
      shell: bash
      run: |
        # Add wamrc to PATH
        echo "${{ github.workspace }}/vendor/wamr/wamr-compiler/build" >> $GITHUB_PATH
