name: 'Setup EdgeBox'
description: 'Setup EdgeBox build environment with all dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '20'
  install-hyperfine:
    description: 'Install hyperfine for benchmarking'
    required: false
    default: 'false'
  install-porffor:
    description: 'Install Porffor JS-to-WASM compiler'
    required: false
    default: 'false'
  build-test262:
    description: 'Build test262 runner'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Porffor
      if: inputs.install-porffor == 'true'
      shell: bash
      run: npm install -g porffor

    - name: Install hyperfine
      if: inputs.install-hyperfine == 'true'
      shell: bash
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-musl_1.20.0_amd64.deb
        sudo dpkg -i hyperfine-musl_1.20.0_amd64.deb

    - name: Install LLVM for WAMR AOT compiler
      shell: bash
      run: sudo apt-get install -y llvm-18-dev

    - name: Build Binaryen from source
      shell: bash
      run: |
        sudo apt-get install -y cmake ninja-build
        git clone --depth 1 --branch version_119 https://github.com/WebAssembly/binaryen.git /tmp/binaryen
        cd /tmp/binaryen
        # Skip tests - we don't need googletest submodule
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_TESTS=OFF .
        ninja
        sudo ninja install
        sudo ldconfig

    - name: Cache WAMR build
      uses: actions/cache@v4
      with:
        path: vendor/wamr/product-mini/platforms/linux/build
        key: wamr-linux-simd-v2-${{ hashFiles('vendor/wamr/core/version.h', 'vendor/wamr/product-mini/platforms/linux/CMakeLists.txt', 'scripts/build-wamr.sh', 'build.zig') }}

    - name: Build WAMR
      shell: bash
      run: ./scripts/build-wamr.sh

    - name: Build EdgeBox
      shell: bash
      run: |
        zig build wasm -Doptimize=ReleaseFast
        zig build runner -Doptimize=ReleaseFast
        zig build cli -Doptimize=ReleaseFast
        ${{ inputs.build-test262 == 'true' && 'zig build test262 -Doptimize=ReleaseFast' || '' }}
