name: 'Setup EdgeBox'
description: 'Setup EdgeBox build environment with all dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '20'
  install-hyperfine:
    description: 'Install hyperfine for benchmarking'
    required: false
    default: 'false'
  install-porffor:
    description: 'Install Porffor JS-to-WASM compiler'
    required: false
    default: 'false'
  build-test262:
    description: 'Build test262 runner'
    required: false
    default: 'false'
  build-benchmarks:
    description: 'Build all benchmark WASM files'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    # === Tool Setup (always needed) ===
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Porffor
      if: inputs.install-porffor == 'true'
      shell: bash
      run: npm install -g porffor

    - name: Install hyperfine
      if: inputs.install-hyperfine == 'true'
      shell: bash
      run: |
        if [[ "$OSTYPE" == "darwin"* ]]; then
          brew install hyperfine
        else
          wget -q https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-musl_1.20.0_amd64.deb
          sudo dpkg -i hyperfine-musl_1.20.0_amd64.deb
        fi

    - name: Install build dependencies
      shell: bash
      run: |
        if [[ "$OSTYPE" == "darwin"* ]]; then
          # macOS
          brew install llvm@18 cmake ninja
        else
          # Linux
          sudo apt-get update
          sudo apt-get install -y llvm-18 llvm-18-dev cmake ninja-build

          # Find and symlink libLLVM.so for Zig
          echo "Searching for libLLVM..."
          find /usr/lib -name "libLLVM*" 2>/dev/null || true

          # Try common locations
          if [ -f /usr/lib/llvm-18/lib/libLLVM.so ]; then
            sudo ln -sf /usr/lib/llvm-18/lib/libLLVM.so /usr/lib/x86_64-linux-gnu/libLLVM.so
          elif [ -f /usr/lib/llvm-18/lib/libLLVM-18.so ]; then
            sudo ln -sf /usr/lib/llvm-18/lib/libLLVM-18.so /usr/lib/x86_64-linux-gnu/libLLVM.so
          elif [ -f /usr/lib/llvm-18/lib/libLLVM-18.so.1 ]; then
            sudo ln -sf /usr/lib/llvm-18/lib/libLLVM-18.so.1 /usr/lib/x86_64-linux-gnu/libLLVM.so
          else
            echo "ERROR: libLLVM not found in /usr/lib/llvm-18/lib/"
            exit 1
          fi

          echo "Created symlink:"
          ls -la /usr/lib/x86_64-linux-gnu/libLLVM.so
        fi

    # === Cache ALL build outputs ===
    - name: Cache EdgeBox build
      id: cache-edgebox
      uses: actions/cache@v4
      with:
        path: |
          zig-out/bin/
          zig-out/cache/
          vendor/binaryen/
          vendor/wamr/product-mini/platforms/*/build/
        key: edgebox-full-v5-${{ runner.os }}-${{ hashFiles('build.zig', 'scripts/build-wamr.sh', 'vendor/wamr/core/version.h', 'src/**/*.zig', 'src/freeze/*.zig', 'bench/*.js', 'src/polyfills/*.js') }}

    # === Build Binaryen (if cache miss) ===
    - name: Build Binaryen
      if: steps.cache-edgebox.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # Clone binaryen if not exists (not a submodule)
        if [ ! -d vendor/binaryen ]; then
          git clone --depth 1 --branch version_119 https://github.com/WebAssembly/binaryen.git vendor/binaryen
        fi
        cd vendor/binaryen
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF .
        ninja -C build
        # Install system-wide for Zig to find
        sudo ninja -C build install
        # Update linker cache (Linux only)
        if [[ "$OSTYPE" != "darwin"* ]]; then
          sudo ldconfig
        fi

    # === Build WAMR (if cache miss) ===
    - name: Build WAMR
      if: steps.cache-edgebox.outputs.cache-hit != 'true'
      shell: bash
      run: ./scripts/build-wamr.sh

    # === Build EdgeBox (if cache miss) ===
    - name: Build EdgeBox
      if: steps.cache-edgebox.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # Use baseline CPU for portable binaries (avoid SIGILL on different runners)
        zig build wasm -Doptimize=ReleaseFast
        zig build runner -Doptimize=ReleaseFast -Dcpu=baseline
        zig build cli -Doptimize=ReleaseFast -Dcpu=baseline
        ${{ inputs.build-test262 == 'true' && 'zig build test262 -Doptimize=ReleaseFast -Dcpu=baseline' || '' }}

    # === Build benchmarks (if cache miss and requested) ===
    - name: Build Benchmarks
      if: steps.cache-edgebox.outputs.cache-hit != 'true' && inputs.build-benchmarks == 'true'
      shell: bash
      run: |
        echo "Building all benchmarks..."
        for bench in hello memory fib loop tail_recursive; do
          echo "Building $bench..."
          ./zig-out/bin/edgeboxc build bench/$bench.js
        done
        ls -la zig-out/bin/bench/

    # === Install binaryen system-wide (on cache hit, since build step is skipped) ===
    - name: Install Binaryen (cache hit)
      if: steps.cache-edgebox.outputs.cache-hit == 'true'
      shell: bash
      run: |
        cd vendor/binaryen
        sudo ninja -C build install
        # Update linker cache (Linux only)
        if [[ "$OSTYPE" != "darwin"* ]]; then
          sudo ldconfig
        fi

    # === Build test262 (on cache hit, if requested) ===
    - name: Build test262 (cache hit)
      if: steps.cache-edgebox.outputs.cache-hit == 'true' && inputs.build-test262 == 'true'
      shell: bash
      run: |
        zig build test262 -Doptimize=ReleaseFast -Dcpu=baseline

    # === Build AOT for test262 (always needed for test262 runs) ===
    - name: Build AOT base module
      if: inputs.build-test262 == 'true'
      shell: bash
      run: |
        echo "Building AOT compiler and base AOT module..."
        zig build aot-tool -Doptimize=ReleaseFast -Dcpu=baseline
        ./zig-out/bin/edgebox-aot zig-out/bin/edgebox-base.wasm zig-out/bin/edgebox-base.aot
        ls -lh zig-out/bin/edgebox-base.aot

    # === Setup environment (always needed, even on cache hit) ===
    - name: Setup paths
      shell: bash
      run: |
        # Add edgebox CLI to PATH
        echo "${{ github.workspace }}/zig-out/bin" >> $GITHUB_PATH
